version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: /w
    machine: true
    steps:
      - checkout
      - run:
          name: check-binaries
          command: |
            which git || apk add git;
            which curl || apk add curl;
            which bash || apk add bash;
      - run:
          name: build-images
          command: |
            chmod a+x build.sh params.sh;
            /bin/bash build.sh;
