version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: docker:19.03.13
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: check-binaries
          command: |
            which git || apk add git;
            which curl || apk add curl;
            which bash || apk add bash;
      - run:
          name: build-images
          command: |
            chmod a+x build.sh params.sh;
            /bin/bash build.sh;
