version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/w
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: check-binaries
          command: |
            sudo apt update;
            which git || sudo apt install --no-install-recommends -y git;
            which curl || sudo apt install --no-install-recommends -y curl;
            which bash || sudo apt install --no-install-recommends -y bash;
      - run:
          name: build-images
          command: |
            chmod a+x build.sh params.sh;
            sudo DOCKER_USER=${DOCKER_USER} DOCKER_PASSWORD=${DOCKER_PASSWORD} GOOGLE_API_KEY=${GOOGLE_API_KEY} ./build.sh;
