version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/w
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: check-binaries
          command: |
            apt update;
            which git || apt install --no-install-recommends -y git;
            which curl || apt install --no-install-recommends -y curl;
            which bash || apt install --no-install-recommends -y bash;
      - run:
          name: build-images
          command: |
            chmod a+x build.sh params.sh;
            /bin/bash build.sh;
